### PR TITLE
update for new dlcs

### PR DESCRIPTION
**Pull request by kruzuahz**
As requested here a PR for the full changeset

-- Old PR --
Added chains for enbasa shepards, elders and scholar, including images.
Added chains for Tourists, and consumed goods in old chains.
Added template for multifactories: orchards(old and new world),chemical plants(old/new), artisan workshops, assemblylines.
Added chains for high life dlc skyscraper consumables/ construction materials.
Added templates for venues: bar, cafe, restaurant, drugstore, furniture store, department store, iron tower.
Added a file for recipes and patents. I managed to fit them one page, but with only the final part of the chain. With the full chain you can fit about 8 on a single page, this gives a better overview I think.

I've added the chains as separate files to make it easier to read (feel free to copy them in if you wish)
Updated arctic icons to 124x124 pix images

-- Newly added in this PR -- 
Added hacienda brewery chains
Added Airmail chains
Added Bright Harvest  DLC chains
include Enbesa and newworld materials on materials page.
Added Cultural item sets (Zoo, Museum, Garden) with effects and applicable music scores.
Added Palace ad Hacienda effects
Added chains for new world dlc
Added Iron tower chains

consumer nodes now display number of residences supplies instead of number residents (same way the game does it)
consumer nodes now also display workforce, happiness, heat, science and money income gotten for supplying the good
now all nodes also display lifestyle needs (TODO good way to see if a need is required or lifestyle)

Moved all chains to own file (except Farmers, i can't get it to fit properly on the page anymore in a separate file)
Fix display errors where some pages are upside down in some pdf viewers (Now uses a different landscape environment)

### CODE REVIEW

**Comment by dotSp0T** [comment]
ToDos for ( @dotSp0T or @McDonnough ):

- [ ] check formatting
- [ ] fit into existing system
- [ ] review numbers

**Comment by McDonnough** [comment]
Formatting and layout looks good to me. Some numbers overlap borders or images, but that's a problem that was always there and hasn't been introduced with the changes in this PR. I haven't checked the numbers yet.

**Comment by McDonnough** [comment]
And I'd create a seperate issue to try if putting the `tex`-files into sub-directories will work and really makes the whole thing more manageable.

**Comment by kruzuahz** [comment]
Hello All,

Agree with McDonnough that we should make a separate issue for the subdirectories

To speed up this PR  we could skip the numbers review for now and allow others user to review / make issues for those. The last few patches have changed things anyway. 

I'm still willing to help out with the release / update the issues when this is merged.

Regards Kruzuahz

**Comment by McDonnough** [comment]
I created #12 to try and see if the subdirectory thing could work and actually help.

And I agree that we could just merge the PR for now and check the numbers after that. It's not like we can't adjust them at a later point.

**Review by McDonnough — APPROVED** [review]

**Comment by McDonnough** [comment]
Unfortunately my approval isn't enough since I don't have write access.

@dotSp0T Can you give your approval as well?

**Review by dotSp0T — APPROVED** [review]
Already checked over by @McDonnough so I'm gonna flag it for go; following tasks will be done at a later time / new PRs:

- fit into existing system
- review numbers
- check if wen can work with subdirectories

**Pull request merged**
